name: CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install

  lint:
    name: Run linting
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn lint

  unittest:
    name: Run unit tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn test
