name: Manually deploy to Firebase Hosting
on: workflow_dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BY_THE_WAY_C3675 }}'
          channelId: live
          projectId: by-the-way-c3675
